config/routes.rb
Rails.application.routes.draw do

  resources :inventories

  root :to => 'inventories#index'

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  validates_presence_of :item, :description, :price, :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, :only => [:show, :edit, :update, :destroy]

  def index
    @inventories = Inventory.page(params[:page]).per(5)
    @inventory = Inventory.new
    flash[:current_page] = current_page_num
  end

  def edit
    @current_page = flash[:current_page]
    flash[:current_page] = flash[:current_page]
  end


  def create
    @inventory = Inventory.new(inventory_param)
    if @inventory.save
      flash[:notice] = "Inventory was successfully created"
      redirect_to_current_page
    else
      render :action => :new
    end
  end

  def show
    @current_page = flash[:current_page]
  end

  def show_back
    flash[:current_page] = flash[:current_page]
    redirect_to_current_page
  end

  def update
    @dumming = @inventory.dup
    if @inventory.update(inventory_param)
      if check_changing(@dumming, @inventory)
        flash[:notice] = "Inventory was successfully updated" 
      else
        flash[:notice] = "Nothing has been changed"
      end 
      redirect_to_current_page
    else
      @current_page = flash[:current_page]
      render :action => :edit
    end
  end

  def destroy
    @current_page = flash[:current_page]
    @inventory.destroy
    redirect_to_current_page
  end

private

  def inventory_param
    params.require(:inventory).permit(:item, :description, :price, :stock, :lack)
  end

  def current_page_num
    params.permit(:page)
  end

  def set_inventory
    @inventory = Inventory.find(params[:id])
  end

  def check_changing(a,b)
    !(a.item == b.item &&
    a.description == b.description &&
    a.price == b.price &&
    a.stock == b.stock &&
    a.lack == b.lack)
  end

  def redirect_to_current_page
    @page_num = "1"
    @page_num = flash[:current_page]["page"] if flash[:current_page].present?
    redirect_to (inventories_path + "?page=" + @page_num)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= f.label :item, "Item" %>
<%= f.text_field :item %>

<%= f.label :description, "Description" %>
<%= f.text_area :description %>

<%= f.label :price, "Price" %>
<%= f.number_field :price %>

<%= f.label :stock, "Stock" %>
<%= f.number_field :stock %>

<%= f.label :lack, "Lack" %>
<%= f.check_box :lack %>

<% if @inventory.errors.any? %>
      <ul>
      <% @inventory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

app/views/inventories/edit.html.erb
<%= form_for @inventory, :url => inventory_path(@inventory), :method => :patch do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>

  <%= f.submit "Update" %>
<% end %>

app/views/inventories/index.html.erb
<div class="container">
  
  <h1>Inventory Management System</h1>
  <div class="row">
    <div class="col-12">
      <table class="table table-hover form-width">
        <% @inventories.each do |i| %>

          <tr>
            <td style="font-size: 20px">
            <%= i.item %>
            </td>
            <td>
            <%= link_to "Show", inventory_path(i), :class => "btn btn-primary" %>
            <%= link_to "Edit", edit_inventory_path(i), :class => "btn btn-info" %>
            <%= link_to "Delete", inventory_path(i), :method => :delete, :class => "btn btn-danger" %>
            </td>
          </tr>
          </li>
        <% end %>
      </table>

      <br>
      <%= paginate @inventories %>

      <br>
    </div>

    <div class="col-12">
      <% if !@inventory_old.present? %>
        <%= form_for @inventory, :url => inventories_path do |f| %>
          <%= render :partial => 'form', :locals => { :f => f } %>

          <%= f.submit "Create" %>
        <% end %>
      <% end %>

      <% if @inventory_old.present?%>
         <%= form_for @inventory_old, :url => inventories_path, :method => :patch do |f| %>
          <%= render :partial => 'form', :locals => { :f => f } %>

          <%= f.submit "Update" %>
        <% end %>
      <% end %>
    </div>


  </div>
</div>

app/views/inventories/new.html.erb
<%= form_for @inventory, :url => inventories_path do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>

  <%= f.submit "Create" %>
<% end %>

app/views/inventories/show.html.erb
<div class="container">
  <h1>Inventories list</h1>

  <table class="table table-striped">
    <tr>
      <th>
        Item
      </th>
      <th>
        Description
      </th>
      <th>
        Price
      </th>
      <th>
        Stock
      </th>
      <th>
        Lack
      </th>
      <th>
        Value
      </th>
    </tr>

    <tr>
      <td>
        <%= @inventory.item %>
      </td>
      <td>
        <%= @inventory.description %>
      </td>
      <td>
        $ <%= @inventory.price %>
      </td>
      <td>
        <%= @inventory.stock %>
      </td>
      <td>
        <% @lack = "no" %>
        <% @lack = "Yes" if @inventory.lack != nil %>
        <%= @lack %>
      </td>
      <td>
        $ <%= @inventory.price * @inventory.stock %>
      </td>
    </tr>

  </table>
  <% @page_num = "1" %>
  <% @page_num = @current_page["page"] if @current_page .present? %>
  <p><%= link_to 'Back to index', inventories_path + "?page=" + @page_num , :class => "btn btn-info" %> </p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OMS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container">

    <% if flash[:notice].present? %>
      <div class="alert alert-success"> 
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:alert].present? %>
      <div class="alert alert-danger ">
        <%= flash[:alert] %></div>
      </div>
    <% end %>

  <%= yield %>

</body>
</html>